services:
  {{ service_name }}:
    image: docker.io/twingate/connector:{{ twingate_version }}
        {% if not swarm_enabled %}
    restart: {{ restart_policy }}
    container_name: {{ container_name }}
    {% endif %}
        hostname: {{ container_hostname }}
        environment:
      - TZ={{ container_timezone }}
      - TWINGATE_NETWORK={{ twingate_network }}
      {% if swarm_enabled %}
      - TWINGATE_ACCESS_TOKEN=/run/secrets/twingate_access_token
      - TWINGATE_REFRESH_TOKEN=/run/secrets/twingate_refresh_token
      {% else %}
      - TWINGATE_ACCESS_TOKEN=${TWINGATE_ACCESS_TOKEN:?error}
      - TWINGATE_REFRESH_TOKEN=${TWINGATE_REFRESH_TOKEN:?error}
      {% endif %}
      - TWINGATE_LOG_LEVEL={{ twingate_log_level }}
      {% if twingate_dns %}
      - TWINGATE_DNS={{ twingate_dns }}
      {% endif %}
        sysctls:
      net.ipv4.ping_group_range: "0 2147483647"
        {% if swarm_enabled %}
    secrets:
      - twingate_access_token
      - twingate_refresh_token
    deploy:
      {% if swarm_placement_mode == 'replicated' %}
      replicas: {{ swarm_replicas }}
      placement:
        constraints:
          - node.hostname == {{ swarm_placement_host }}
      {% else %}
      mode: global
      {% endif %}
      restart_policy:
        condition: on-failure
      {% if resources_enabled %}
      resources:
        limits:
          cpus: '{{ resources_cpu_limit }}'
          memory: {{ resources_memory_limit }}
        reservations:
          cpus: '{{ resources_cpu_reservation }}'
          memory: {{ resources_memory_reservation }}
      {% endif %}
    {% endif %}

{% if swarm_enabled %}
secrets:
  twingate_access_token:
    external: true
  twingate_refresh_token:
    external: true
{% endif %}
