---
- name: Docker cleanup
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Docker cleanup
      community.docker.docker_prune:
        containers: "{{ cleanup_containers | default(false) | bool }}"
        images: true
        images_filters:
          dangling: "{{ false if (cleanup_nondangling | default(false) | bool) else true }}"
        networks: "{{ cleanup_networks | default(false) | bool }}"
        volumes: "{{ cleanup_volumes | default(false) | bool }}"
        builder_cache: false
