apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-data
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  # --> (Optional) Enable this section if you are using NFS
  # storageClassName: nfs
  # nfs:
  #   server: nfs-server-ip
  #   path: "/your-nfs-path"
  # <--
