services:
  {{ service_name }}:
    image: docker.io/library/postgres:18.2
        {% if not swarm_enabled %}
    restart: {{ restart_policy }}
    container_name: {{ container_name }}
    {% endif %}
        hostname: {{ container_hostname }}
        environment:
      - POSTGRES_INITDB_ARGS={{ postgres_initdb_args }}
      {% if postgres_host_auth_method %}
      - POSTGRES_HOST_AUTH_METHOD={{ postgres_host_auth_method }}
      {% endif %}
      - POSTGRES_USER={{ database_user }}
      {% if postgres_secrets_enabled %}
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      {% else %}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      {% endif %}
      - POSTGRES_DB={{ database_name }}
      - TZ={{ container_timezone }}
        {% if network_mode == 'bridge' or network_mode == '' %}
    networks:
      {{ network_name }}:
    {% endif %}
        {% if network_mode == 'bridge' or network_mode == '' %}
    ports:
      {% if swarm_enabled %}
      - target: 5432
        published: {{ database_port }}
        protocol: tcp
        mode: host
      {% else %}
      - "{{ database_port }}:5432"
      {% endif %}
    {% endif %}
        volumes:
      {% if volume_mode == 'mount' %}
      - {{ volume_mount_path }}:/var/lib/postgresql/data:rw
      {% else %}
      - {{ service_name }}-data:/var/lib/postgresql/data
      {% endif %}
        {% if postgres_secrets_enabled %}
    secrets:
      - postgres_password
    {% endif %}
        healthcheck:
      test: ["CMD-SHELL", "pg_isready -U {{ database_user }}"]
      start_period: 30s
      interval: 10s
      timeout: 10s
      retries: 5
        {% if swarm_enabled %}
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    {% endif %}

{% if postgres_secrets_enabled %}
secrets:
  postgres_password:
    file: secret.postgres_password.txt
{% endif %}

{% if volume_mode == 'local' %}
volumes:
  {{ service_name }}-data:
    driver: local
{% elif volume_mode == 'nfs' %}
volumes:
  {{ service_name }}-data:
    driver: local
    driver_opts:
      type: nfs
      o: addr={{ volume_nfs_server }},{{ volume_nfs_options }}
      device: ":{{ volume_nfs_path }}"
{% endif %}

{% if network_mode == 'bridge' or network_mode == '' %}
networks:
  {{ network_name }}:
    {% if network_external %}
    external: true
    {% else %}
    {% if swarm_enabled %}
    driver: overlay
    attachable: true
    {% else %}
    driver: bridge
    {% endif %}
    {% endif %}
{% endif %}
