#!/usr/bin/env python3
"""Generate wiki documentation for module schemas.

This script generates markdown documentation for module variable specifications.
It reads the schema definitions from cli/modules and creates formatted markdown
files in docs/wiki/ directory.

Usage:
    python3 scripts/docs_generate_schema.py compose 1.1
    python3 scripts/docs_generate_schema.py compose --all
    python3 scripts/docs_generate_schema.py --all-modules
"""

import argparse
import importlib.util
import sys
from pathlib import Path
from collections import OrderedDict
from typing import Dict, List, Any, Optional


def load_module_spec(module_name: str, schema_version: str) -> Optional[OrderedDict]:
    """Load spec from module schema file.

    Args:
      module_name: Name of the module (e.g., 'compose')
      schema_version: Schema version (e.g., '1.0', '1.1')

    Returns:
      OrderedDict with the spec or None if not found
    """
    # Construct path to spec file
    spec_file = (
        Path(__file__).parent.parent
        / "cli"
        / "modules"
        / module_name
        / f"spec_v{schema_version.replace('.', '_')}.py"
    )

    if not spec_file.exists():
        return None

    # Load the module
    spec_name = f"spec_v{schema_version.replace('.', '_')}"
    spec = importlib.util.spec_from_file_location(spec_name, spec_file)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    return module.spec


def get_available_schemas(module_name: str) -> List[str]:
    """Get list of available schema versions for a module.

    Args:
      module_name: Name of the module

    Returns:
      List of schema version strings (e.g., ['1.0', '1.1'])
    """
    module_dir = Path(__file__).parent.parent / "cli" / "modules" / module_name

    if not module_dir.exists():
        return []

    schemas = []
    for spec_file in module_dir.glob("spec_v*.py"):
        version = spec_file.stem.replace("spec_v", "").replace("_", ".")
        schemas.append(version)

    return sorted(schemas)


def format_variable_type(var_data: Dict[str, Any]) -> str:
    """Format variable type with options if enum.

    Args:
      var_data: Variable data dictionary

    Returns:
      Formatted type string
    """
    var_type = var_data.get("type", "str")

    if var_type == "enum" and "options" in var_data:
        options = ", ".join(f"`{opt}`" for opt in var_data["options"])
        return f"enum ({options})"

    return f"`{var_type}`"


def format_default_value(var_data: Dict[str, Any]) -> str:
    """Format default value for display.

    Args:
      var_data: Variable data dictionary

    Returns:
      Formatted default value string
    """
    if "default" not in var_data:
        return "-"

    default = var_data["default"]

    if default is None or default == "":
        if var_data.get("autogenerated"):
            return "*auto-generated*"
        return "-"

    if isinstance(default, bool):
        return f"`{str(default).lower()}`"

    if isinstance(default, str):
        return f"`{default}`"

    return f"`{default}`"


def format_dependencies(var_data: Dict[str, Any]) -> str:
    """Format variable dependencies/needs.

    Args:
      var_data: Variable data dictionary

    Returns:
      Formatted dependency string
    """
    if "needs" not in var_data:
        return "-"

    needs = var_data["needs"]
    return f"`{needs}`"


def generate_section_markdown(section_key: str, section_data: Dict[str, Any]) -> str:
    """Generate markdown for a section.

    Args:
      section_key: Section key
      section_data: Section data dictionary

    Returns:
      Markdown string for the section
    """
    title = section_data.get("title", section_key.replace("_", " ").title())
    description = section_data.get("description", "")
    toggle = section_data.get("toggle")
    required = section_data.get("required", section_key == "general")
    needs = section_data.get("needs")

    md = [f"### {title}"]

    if description:
        md.append(f"\n{description}\n")

    # Section metadata
    metadata = []
    if required:
        metadata.append("**Required Section**")
    if toggle:
        default_val = section_data.get("vars", {}).get(toggle, {}).get("default", False)
        metadata.append(
            f"**Toggle:** `{toggle}` (default: `{str(default_val).lower()}`)"
        )
    if needs:
        if isinstance(needs, list):
            needs_str = ", ".join(f"`{n}`" for n in needs)
        else:
            needs_str = f"`{needs}`"
        metadata.append(f"**Depends on:** {needs_str}")

    if metadata:
        md.append("")
        md.extend(metadata)

    # Variables table
    vars_data = section_data.get("vars", {})
    if vars_data:
        md.append("\n| Variable | Type | Default | Dependencies | Description |")
        md.append("|----------|------|---------|--------------|-------------|")

        for var_name, var_data in vars_data.items():
            var_type = format_variable_type(var_data)
            default = format_default_value(var_data)
            deps = format_dependencies(var_data)
            desc = var_data.get("description", "")

            # Add extra info if available
            if "extra" in var_data:
                desc += f"<br>*{var_data['extra']}*"

            # Mark sensitive variables
            if var_data.get("sensitive"):
                desc += " 🔒"

            md.append(f"| `{var_name}` | {var_type} | {default} | {deps} | {desc} |")

    md.append("")
    return "\n".join(md)


def generate_schema_markdown(
    module_name: str, schema_version: str, spec: OrderedDict
) -> str:
    """Generate complete markdown documentation for a schema.

    Args:
      module_name: Name of the module
      schema_version: Schema version
      spec: Schema specification OrderedDict

    Returns:
      Complete markdown document
    """
    md = [
        f"# {module_name.capitalize()} Module - Variables Reference",
        f"\n**Schema Version:** `{schema_version}`\n",
        "This page documents all available variables for the module schema.",
        "Variables are organized into sections, and some sections may be optional (toggled).",
        "\n---\n",
    ]

    # Generate sections
    for section_key, section_data in spec.items():
        md.append(generate_section_markdown(section_key, section_data))

    # Footer
    md.extend(
        [
            "---",
            "",
            "## Legend",
            "",
            "- 🔒 = Sensitive variable (masked in prompts)",
            "- *auto-generated* = Value automatically generated if not provided",
            "- **Toggle** = Boolean variable that enables/disables the entire section",
            "- **Depends on** = Section only active when dependencies are satisfied",
            "",
        ]
    )

    return "\n".join(md)


def save_markdown(module_name: str, schema_version: str, content: str) -> Path:
    """Save markdown content to file.

    Args:
      module_name: Name of the module
      schema_version: Schema version
      content: Markdown content

    Returns:
      Path to saved file
    """
    # Create docs/wiki directory if it doesn't exist
    wiki_dir = Path(__file__).parent.parent / "docs" / "wiki"
    wiki_dir.mkdir(parents=True, exist_ok=True)

    # Generate filename following GitHub Wiki conventions
    # Format: Modules-{Module}-Variables-v{Version}
    filename = f"Modules-{module_name.capitalize()}-Variables-v{schema_version}.md"
    filepath = wiki_dir / filename

    # Write file
    filepath.write_text(content)

    return filepath


def main():
    parser = argparse.ArgumentParser(
        description="Generate wiki documentation for module schemas"
    )
    parser.add_argument("module", nargs="?", help="Module name (e.g., compose)")
    parser.add_argument(
        "schema", nargs="?", help="Schema version (e.g., 1.1) or --all for all schemas"
    )
    parser.add_argument(
        "--all-modules", action="store_true", help="Generate docs for all modules"
    )
    parser.add_argument(
        "--all", action="store_true", help="Generate docs for all schemas of the module"
    )

    args = parser.parse_args()

    # Validate arguments
    if not args.all_modules and not args.module:
        parser.error("module name is required unless --all-modules is specified")

    if args.all_modules:
        # Find all modules
        modules_dir = Path(__file__).parent.parent / "cli" / "modules"
        modules = [
            d.name
            for d in modules_dir.iterdir()
            if d.is_dir() and not d.name.startswith("_")
        ]

        for module_name in modules:
            schemas = get_available_schemas(module_name)
            if not schemas:
                print(f"No schemas found for module: {module_name}")
                continue

            print(f"\nGenerating docs for module: {module_name}")
            for schema_version in schemas:
                generate_for_schema(module_name, schema_version)

    elif args.all or args.schema == "--all":
        # Generate all schemas for module
        schemas = get_available_schemas(args.module)
        if not schemas:
            print(f"No schemas found for module: {args.module}")
            sys.exit(1)

        print(f"Found schemas for {args.module}: {', '.join(schemas)}")
        for schema_version in schemas:
            generate_for_schema(args.module, schema_version)

    else:
        # Generate single schema
        if not args.schema:
            parser.error("schema version is required unless --all is specified")

        generate_for_schema(args.module, args.schema)


def generate_for_schema(module_name: str, schema_version: str):
    """Generate documentation for a specific module and schema.

    Args:
      module_name: Name of the module
      schema_version: Schema version
    """
    spec = load_module_spec(module_name, schema_version)

    if spec is None:
        print(f"Error: Schema {schema_version} not found for module {module_name}")
        sys.exit(1)

    print(f"Generating documentation for {module_name} v{schema_version}...")

    markdown = generate_schema_markdown(module_name, schema_version, spec)
    filepath = save_markdown(module_name, schema_version, markdown)

    print(f"  Created: {filepath}")


if __name__ == "__main__":
    main()
